"""Public geometry API for Kroika's deterministic pattern engine."""

from .diagnostics import GEOMETRY_CORE_VERSION, run_core_diagnostics
from .errors import (
    ConvergenceError,
    DegenerateGeometryError,
    DisconnectedContourError,
    GeometryError,
    InvalidCoordinateError,
    InvalidParameterError,
    OffsetCollapseError,
    OpenContourError,
    OverlappingGeometryError,
    SelfIntersectionError,
    SerializationError,
    UnsupportedGeometryError,
)
from .intersections import (
    Intersection,
    intersections,
    line_arc_intersections,
    line_line_intersections,
)
from .offset import OffsetResult, offset_arc, offset_contour, offset_line
from .primitives import (
    AffineTransform,
    ArcSegment,
    BoundingBox,
    Contour,
    CubicBezier,
    DEFAULT_TOLERANCE,
    GeometryTolerance,
    LineSegment,
    MAX_ABS_COORDINATE_MM,
    Point,
    Vector,
    curve_points,
)
from .serialization import (
    arc_from_svg_endpoint,
    canonical_json,
    contour_from_data,
    contour_from_json,
    contour_to_data,
    curve_from_data,
    curve_to_data,
)
from .validation import validate_simple_contour

__all__ = [
    "AffineTransform",
    "ArcSegment",
    "BoundingBox",
    "ConvergenceError",
    "Contour",
    "CubicBezier",
    "DEFAULT_TOLERANCE",
    "DegenerateGeometryError",
    "DisconnectedContourError",
    "GeometryError",
    "GEOMETRY_CORE_VERSION",
    "GeometryTolerance",
    "Intersection",
    "InvalidCoordinateError",
    "InvalidParameterError",
    "LineSegment",
    "MAX_ABS_COORDINATE_MM",
    "OffsetCollapseError",
    "OffsetResult",
    "OpenContourError",
    "OverlappingGeometryError",
    "Point",
    "SelfIntersectionError",
    "SerializationError",
    "UnsupportedGeometryError",
    "Vector",
    "arc_from_svg_endpoint",
    "canonical_json",
    "contour_from_data",
    "contour_from_json",
    "contour_to_data",
    "curve_from_data",
    "curve_points",
    "curve_to_data",
    "intersections",
    "line_arc_intersections",
    "line_line_intersections",
    "offset_arc",
    "offset_contour",
    "offset_line",
    "run_core_diagnostics",
    "validate_simple_contour",
]
